[
{ "tag": "typedef", "ns": 0, "name": "__u_char", "location": "/usr/include/bits/types.h:30:23", "type": { "tag": ":unsigned-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "__u_short", "location": "/usr/include/bits/types.h:31:28", "type": { "tag": ":unsigned-short", "bit-size": 16, "bit-alignment": 16 } },
{ "tag": "typedef", "ns": 0, "name": "__u_int", "location": "/usr/include/bits/types.h:32:22", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__u_long", "location": "/usr/include/bits/types.h:33:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__int8_t", "location": "/usr/include/bits/types.h:36:21", "type": { "tag": ":signed-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "__uint8_t", "location": "/usr/include/bits/types.h:37:23", "type": { "tag": ":unsigned-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "__int16_t", "location": "/usr/include/bits/types.h:38:26", "type": { "tag": ":short", "bit-size": 16, "bit-alignment": 16 } },
{ "tag": "typedef", "ns": 0, "name": "__uint16_t", "location": "/usr/include/bits/types.h:39:28", "type": { "tag": ":unsigned-short", "bit-size": 16, "bit-alignment": 16 } },
{ "tag": "typedef", "ns": 0, "name": "__int32_t", "location": "/usr/include/bits/types.h:40:20", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__uint32_t", "location": "/usr/include/bits/types.h:41:22", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__int64_t", "location": "/usr/include/bits/types.h:43:25", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__uint64_t", "location": "/usr/include/bits/types.h:44:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__int_least8_t", "location": "/usr/include/bits/types.h:51:18", "type": { "tag": "__int8_t" } },
{ "tag": "typedef", "ns": 0, "name": "__uint_least8_t", "location": "/usr/include/bits/types.h:52:19", "type": { "tag": "__uint8_t" } },
{ "tag": "typedef", "ns": 0, "name": "__int_least16_t", "location": "/usr/include/bits/types.h:53:19", "type": { "tag": "__int16_t" } },
{ "tag": "typedef", "ns": 0, "name": "__uint_least16_t", "location": "/usr/include/bits/types.h:54:20", "type": { "tag": "__uint16_t" } },
{ "tag": "typedef", "ns": 0, "name": "__int_least32_t", "location": "/usr/include/bits/types.h:55:19", "type": { "tag": "__int32_t" } },
{ "tag": "typedef", "ns": 0, "name": "__uint_least32_t", "location": "/usr/include/bits/types.h:56:20", "type": { "tag": "__uint32_t" } },
{ "tag": "typedef", "ns": 0, "name": "__int_least64_t", "location": "/usr/include/bits/types.h:57:19", "type": { "tag": "__int64_t" } },
{ "tag": "typedef", "ns": 0, "name": "__uint_least64_t", "location": "/usr/include/bits/types.h:58:20", "type": { "tag": "__uint64_t" } },
{ "tag": "typedef", "ns": 0, "name": "__quad_t", "location": "/usr/include/bits/types.h:62:18", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__u_quad_t", "location": "/usr/include/bits/types.h:63:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__intmax_t", "location": "/usr/include/bits/types.h:71:18", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__uintmax_t", "location": "/usr/include/bits/types.h:72:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__dev_t", "location": "/usr/include/bits/types.h:143:25", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__uid_t", "location": "/usr/include/bits/types.h:144:25", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__gid_t", "location": "/usr/include/bits/types.h:145:25", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__ino_t", "location": "/usr/include/bits/types.h:146:25", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__ino64_t", "location": "/usr/include/bits/types.h:147:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__mode_t", "location": "/usr/include/bits/types.h:148:26", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__nlink_t", "location": "/usr/include/bits/types.h:149:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__off_t", "location": "/usr/include/bits/types.h:150:25", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__off64_t", "location": "/usr/include/bits/types.h:151:27", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__pid_t", "location": "/usr/include/bits/types.h:152:25", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsid_t", "location": "/usr/include/bits/types.h:153:26", "type": { "tag": "struct", "ns": 2147598111, "name": "", "id": 1, "location": "/usr/include/bits/types.h:153:12 <Spelling=/usr/include/bits/typesizes.h:72:24>", "bit-size": 64, "bit-alignment": 32, "fields": [{ "tag": "field", "name": "__val", "bit-offset": 0, "bit-size": 64, "bit-alignment": 32, "type": { "tag": ":array", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 }, "size": 2 } }] } },
{ "tag": "typedef", "ns": 0, "name": "__clock_t", "location": "/usr/include/bits/types.h:154:27", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__rlim_t", "location": "/usr/include/bits/types.h:155:26", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__rlim64_t", "location": "/usr/include/bits/types.h:156:28", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__id_t", "location": "/usr/include/bits/types.h:157:24", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__time_t", "location": "/usr/include/bits/types.h:158:26", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__useconds_t", "location": "/usr/include/bits/types.h:159:30", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__suseconds_t", "location": "/usr/include/bits/types.h:160:31", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__daddr_t", "location": "/usr/include/bits/types.h:162:27", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__key_t", "location": "/usr/include/bits/types.h:163:25", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__clockid_t", "location": "/usr/include/bits/types.h:166:29", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__timer_t", "location": "/usr/include/bits/types.h:169:27", "type": { "tag": ":pointer", "type": { "tag": ":void" } } },
{ "tag": "typedef", "ns": 0, "name": "__blksize_t", "location": "/usr/include/bits/types.h:172:29", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__blkcnt_t", "location": "/usr/include/bits/types.h:177:28", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__blkcnt64_t", "location": "/usr/include/bits/types.h:178:30", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsblkcnt_t", "location": "/usr/include/bits/types.h:181:30", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsblkcnt64_t", "location": "/usr/include/bits/types.h:182:32", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsfilcnt_t", "location": "/usr/include/bits/types.h:185:30", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsfilcnt64_t", "location": "/usr/include/bits/types.h:186:32", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__fsword_t", "location": "/usr/include/bits/types.h:189:28", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__ssize_t", "location": "/usr/include/bits/types.h:191:27", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__syscall_slong_t", "location": "/usr/include/bits/types.h:194:33", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__syscall_ulong_t", "location": "/usr/include/bits/types.h:196:33", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__loff_t", "location": "/usr/include/bits/types.h:200:19", "type": { "tag": "__off64_t" } },
{ "tag": "typedef", "ns": 0, "name": "__caddr_t", "location": "/usr/include/bits/types.h:201:15", "type": { "tag": ":pointer", "type": { "tag": ":char", "bit-size": 8, "bit-alignment": 8 } } },
{ "tag": "typedef", "ns": 0, "name": "__intptr_t", "location": "/usr/include/bits/types.h:204:25", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__socklen_t", "location": "/usr/include/bits/types.h:207:23", "type": { "tag": ":unsigned-int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "__sig_atomic_t", "location": "/usr/include/bits/types.h:212:13", "type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int8_t", "location": "/usr/include/bits/stdint-intn.h:24:18", "type": { "tag": "__int8_t" } },
{ "tag": "typedef", "ns": 0, "name": "int16_t", "location": "/usr/include/bits/stdint-intn.h:25:19", "type": { "tag": "__int16_t" } },
{ "tag": "typedef", "ns": 0, "name": "int32_t", "location": "/usr/include/bits/stdint-intn.h:26:19", "type": { "tag": "__int32_t" } },
{ "tag": "typedef", "ns": 0, "name": "int64_t", "location": "/usr/include/bits/stdint-intn.h:27:19", "type": { "tag": "__int64_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint8_t", "location": "/usr/include/bits/stdint-uintn.h:24:19", "type": { "tag": "__uint8_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint16_t", "location": "/usr/include/bits/stdint-uintn.h:25:20", "type": { "tag": "__uint16_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint32_t", "location": "/usr/include/bits/stdint-uintn.h:26:20", "type": { "tag": "__uint32_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint64_t", "location": "/usr/include/bits/stdint-uintn.h:27:20", "type": { "tag": "__uint64_t" } },
{ "tag": "typedef", "ns": 0, "name": "int_least8_t", "location": "/usr/include/stdint.h:43:24", "type": { "tag": "__int_least8_t" } },
{ "tag": "typedef", "ns": 0, "name": "int_least16_t", "location": "/usr/include/stdint.h:44:25", "type": { "tag": "__int_least16_t" } },
{ "tag": "typedef", "ns": 0, "name": "int_least32_t", "location": "/usr/include/stdint.h:45:25", "type": { "tag": "__int_least32_t" } },
{ "tag": "typedef", "ns": 0, "name": "int_least64_t", "location": "/usr/include/stdint.h:46:25", "type": { "tag": "__int_least64_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least8_t", "location": "/usr/include/stdint.h:49:25", "type": { "tag": "__uint_least8_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least16_t", "location": "/usr/include/stdint.h:50:26", "type": { "tag": "__uint_least16_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least32_t", "location": "/usr/include/stdint.h:51:26", "type": { "tag": "__uint_least32_t" } },
{ "tag": "typedef", "ns": 0, "name": "uint_least64_t", "location": "/usr/include/stdint.h:52:26", "type": { "tag": "__uint_least64_t" } },
{ "tag": "typedef", "ns": 0, "name": "int_fast8_t", "location": "/usr/include/stdint.h:58:22", "type": { "tag": ":signed-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast16_t", "location": "/usr/include/stdint.h:60:19", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast32_t", "location": "/usr/include/stdint.h:61:19", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "int_fast64_t", "location": "/usr/include/stdint.h:62:19", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast8_t", "location": "/usr/include/stdint.h:71:24", "type": { "tag": ":unsigned-char", "bit-size": 8, "bit-alignment": 8 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast16_t", "location": "/usr/include/stdint.h:73:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast32_t", "location": "/usr/include/stdint.h:74:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uint_fast64_t", "location": "/usr/include/stdint.h:75:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "intptr_t", "location": "/usr/include/stdint.h:87:19", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "uintptr_t", "location": "/usr/include/stdint.h:90:27", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "typedef", "ns": 0, "name": "intmax_t", "location": "/usr/include/stdint.h:101:21", "type": { "tag": "__intmax_t" } },
{ "tag": "typedef", "ns": 0, "name": "uintmax_t", "location": "/usr/include/stdint.h:102:22", "type": { "tag": "__uintmax_t" } },
{ "tag": "enum", "ns": 0, "name": "RENDERDOC_CaptureOption", "id": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:75:14", "fields": [{ "tag": "field", "name": "eRENDERDOC_Option_AllowVSync", "value": 0 }, { "tag": "field", "name": "eRENDERDOC_Option_AllowFullscreen", "value": 1 }, { "tag": "field", "name": "eRENDERDOC_Option_APIValidation", "value": 2 }, { "tag": "field", "name": "eRENDERDOC_Option_DebugDeviceMode", "value": 2 }, { "tag": "field", "name": "eRENDERDOC_Option_CaptureCallstacks", "value": 3 }, { "tag": "field", "name": "eRENDERDOC_Option_CaptureCallstacksOnlyDraws", "value": 4 }, { "tag": "field", "name": "eRENDERDOC_Option_DelayForDebugger", "value": 5 }, { "tag": "field", "name": "eRENDERDOC_Option_VerifyBufferAccess", "value": 6 }, { "tag": "field", "name": "eRENDERDOC_Option_VerifyMapWrites", "value": 6 }, { "tag": "field", "name": "eRENDERDOC_Option_HookIntoChildren", "value": 7 }, { "tag": "field", "name": "eRENDERDOC_Option_RefAllResources", "value": 8 }, { "tag": "field", "name": "eRENDERDOC_Option_SaveAllInitials", "value": 9 }, { "tag": "field", "name": "eRENDERDOC_Option_CaptureAllCmdLists", "value": 10 }, { "tag": "field", "name": "eRENDERDOC_Option_DebugOutputMute", "value": 11 }, { "tag": "field", "name": "eRENDERDOC_Option_AllowUnsupportedVendorExtensions", "value": 12 }] },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_CaptureOption", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:216:3", "type": { "tag": ":enum", "name": "RENDERDOC_CaptureOption", "id": 0 } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_CC", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:222:13", "type": { "tag": ":function" } },
{ "tag": "enum", "ns": 0, "name": "RENDERDOC_InputButton", "id": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:235:14", "fields": [{ "tag": "field", "name": "eRENDERDOC_Key_0", "value": 48 }, { "tag": "field", "name": "eRENDERDOC_Key_1", "value": 49 }, { "tag": "field", "name": "eRENDERDOC_Key_2", "value": 50 }, { "tag": "field", "name": "eRENDERDOC_Key_3", "value": 51 }, { "tag": "field", "name": "eRENDERDOC_Key_4", "value": 52 }, { "tag": "field", "name": "eRENDERDOC_Key_5", "value": 53 }, { "tag": "field", "name": "eRENDERDOC_Key_6", "value": 54 }, { "tag": "field", "name": "eRENDERDOC_Key_7", "value": 55 }, { "tag": "field", "name": "eRENDERDOC_Key_8", "value": 56 }, { "tag": "field", "name": "eRENDERDOC_Key_9", "value": 57 }, { "tag": "field", "name": "eRENDERDOC_Key_A", "value": 65 }, { "tag": "field", "name": "eRENDERDOC_Key_B", "value": 66 }, { "tag": "field", "name": "eRENDERDOC_Key_C", "value": 67 }, { "tag": "field", "name": "eRENDERDOC_Key_D", "value": 68 }, { "tag": "field", "name": "eRENDERDOC_Key_E", "value": 69 }, { "tag": "field", "name": "eRENDERDOC_Key_F", "value": 70 }, { "tag": "field", "name": "eRENDERDOC_Key_G", "value": 71 }, { "tag": "field", "name": "eRENDERDOC_Key_H", "value": 72 }, { "tag": "field", "name": "eRENDERDOC_Key_I", "value": 73 }, { "tag": "field", "name": "eRENDERDOC_Key_J", "value": 74 }, { "tag": "field", "name": "eRENDERDOC_Key_K", "value": 75 }, { "tag": "field", "name": "eRENDERDOC_Key_L", "value": 76 }, { "tag": "field", "name": "eRENDERDOC_Key_M", "value": 77 }, { "tag": "field", "name": "eRENDERDOC_Key_N", "value": 78 }, { "tag": "field", "name": "eRENDERDOC_Key_O", "value": 79 }, { "tag": "field", "name": "eRENDERDOC_Key_P", "value": 80 }, { "tag": "field", "name": "eRENDERDOC_Key_Q", "value": 81 }, { "tag": "field", "name": "eRENDERDOC_Key_R", "value": 82 }, { "tag": "field", "name": "eRENDERDOC_Key_S", "value": 83 }, { "tag": "field", "name": "eRENDERDOC_Key_T", "value": 84 }, { "tag": "field", "name": "eRENDERDOC_Key_U", "value": 85 }, { "tag": "field", "name": "eRENDERDOC_Key_V", "value": 86 }, { "tag": "field", "name": "eRENDERDOC_Key_W", "value": 87 }, { "tag": "field", "name": "eRENDERDOC_Key_X", "value": 88 }, { "tag": "field", "name": "eRENDERDOC_Key_Y", "value": 89 }, { "tag": "field", "name": "eRENDERDOC_Key_Z", "value": 90 }, { "tag": "field", "name": "eRENDERDOC_Key_NonPrintable", "value": 256 }, { "tag": "field", "name": "eRENDERDOC_Key_Divide", "value": 257 }, { "tag": "field", "name": "eRENDERDOC_Key_Multiply", "value": 258 }, { "tag": "field", "name": "eRENDERDOC_Key_Subtract", "value": 259 }, { "tag": "field", "name": "eRENDERDOC_Key_Plus", "value": 260 }, { "tag": "field", "name": "eRENDERDOC_Key_F1", "value": 261 }, { "tag": "field", "name": "eRENDERDOC_Key_F2", "value": 262 }, { "tag": "field", "name": "eRENDERDOC_Key_F3", "value": 263 }, { "tag": "field", "name": "eRENDERDOC_Key_F4", "value": 264 }, { "tag": "field", "name": "eRENDERDOC_Key_F5", "value": 265 }, { "tag": "field", "name": "eRENDERDOC_Key_F6", "value": 266 }, { "tag": "field", "name": "eRENDERDOC_Key_F7", "value": 267 }, { "tag": "field", "name": "eRENDERDOC_Key_F8", "value": 268 }, { "tag": "field", "name": "eRENDERDOC_Key_F9", "value": 269 }, { "tag": "field", "name": "eRENDERDOC_Key_F10", "value": 270 }, { "tag": "field", "name": "eRENDERDOC_Key_F11", "value": 271 }, { "tag": "field", "name": "eRENDERDOC_Key_F12", "value": 272 }, { "tag": "field", "name": "eRENDERDOC_Key_Home", "value": 273 }, { "tag": "field", "name": "eRENDERDOC_Key_End", "value": 274 }, { "tag": "field", "name": "eRENDERDOC_Key_Insert", "value": 275 }, { "tag": "field", "name": "eRENDERDOC_Key_Delete", "value": 276 }, { "tag": "field", "name": "eRENDERDOC_Key_PageUp", "value": 277 }, { "tag": "field", "name": "eRENDERDOC_Key_PageDn", "value": 278 }, { "tag": "field", "name": "eRENDERDOC_Key_Backspace", "value": 279 }, { "tag": "field", "name": "eRENDERDOC_Key_Tab", "value": 280 }, { "tag": "field", "name": "eRENDERDOC_Key_PrtScrn", "value": 281 }, { "tag": "field", "name": "eRENDERDOC_Key_Pause", "value": 282 }, { "tag": "field", "name": "eRENDERDOC_Key_Max", "value": 283 }] },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_InputButton", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:311:3", "type": { "tag": ":enum", "name": "RENDERDOC_InputButton", "id": 0 } },
{ "tag": "enum", "ns": 0, "name": "RENDERDOC_OverlayBits", "id": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:323:14", "fields": [{ "tag": "field", "name": "eRENDERDOC_Overlay_Enabled", "value": 1 }, { "tag": "field", "name": "eRENDERDOC_Overlay_FrameRate", "value": 2 }, { "tag": "field", "name": "eRENDERDOC_Overlay_FrameNumber", "value": 4 }, { "tag": "field", "name": "eRENDERDOC_Overlay_CaptureList", "value": 8 }, { "tag": "field", "name": "eRENDERDOC_Overlay_Default", "value": 15 }, { "tag": "field", "name": "eRENDERDOC_Overlay_All", "value": 4294967295 }, { "tag": "field", "name": "eRENDERDOC_Overlay_None", "value": 0 }] },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_OverlayBits", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:345:3", "type": { "tag": ":enum", "name": "RENDERDOC_OverlayBits", "id": 0 } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_DevicePointer", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:457:15", "type": { "tag": ":pointer", "type": { "tag": ":void" } } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_WindowHandle", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:462:15", "type": { "tag": ":pointer", "type": { "tag": ":void" } } },
{ "tag": "enum", "ns": 0, "name": "RENDERDOC_Version", "id": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:529:14", "fields": [{ "tag": "field", "name": "eRENDERDOC_API_Version_1_0_0", "value": 10000 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_0_1", "value": 10001 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_0_2", "value": 10002 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_1_0", "value": 10100 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_1_1", "value": 10101 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_1_2", "value": 10102 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_2_0", "value": 10200 }, { "tag": "field", "name": "eRENDERDOC_API_Version_1_3_0", "value": 10300 }] },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_Version", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:538:3", "type": { "tag": ":enum", "name": "RENDERDOC_Version", "id": 0 } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_0_0", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:627:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_0_1", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:628:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_0_2", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:629:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_1_0", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:630:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_1_1", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:631:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_1_2", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:632:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "typedef", "ns": 0, "name": "RENDERDOC_API_1_2_0", "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:633:29", "type": { "tag": "RENDERDOC_API_1_3_0" } },
{ "tag": "const", "name": "__S16_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:108:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__inline", "ns": 0, "location": "/usr/include/sys/cdefs.h:77:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "_BITS_STDINT_UINTN_H", "ns": 0, "location": "/usr/include/bits/stdint-uintn.h:20:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__extension__", "ns": 0, "location": "/usr/include/sys/cdefs.h:371:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__WCHAR_MIN", "ns": 0, "location": "/usr/include/bits/wchar.h:44:10", "type": { "tag": ":unsigned-long-long", "bit-size": 64, "bit-alignment": 64 }, "value": 0 },
{ "tag": "const", "name": "_BITS_STDINT_INTN_H", "ns": 0, "location": "/usr/include/bits/stdint-intn.h:20:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__WCHAR_MAX", "ns": 0, "location": "/usr/include/bits/wchar.h:34:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "_BITS_WCHAR_H", "ns": 0, "location": "/usr/include/bits/wchar.h:20:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__restrict", "ns": 0, "location": "/usr/include/sys/cdefs.h:377:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__GLIBC_USE_IEC_60559_TYPES_EXT", "ns": 0, "location": "/usr/include/bits/libc-header-start.h:69:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "_BITS_TYPES_H", "ns": 0, "location": "/usr/include/bits/types.h:24:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__GLIBC_USE_IEC_60559_FUNCS_EXT", "ns": 0, "location": "/usr/include/bits/libc-header-start.h:60:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__GLIBC_USE_LIB_EXT2", "ns": 0, "location": "/usr/include/bits/libc-header-start.h:42:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__GLIBC_USE_IEC_60559_BFP_EXT", "ns": 0, "location": "/usr/include/bits/libc-header-start.h:51:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INTMAX_MIN", "ns": 0, "location": "/usr/include/stdint.h:197:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INTMAX_MAX", "ns": 0, "location": "/usr/include/stdint.h:199:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINTMAX_MAX", "ns": 0, "location": "/usr/include/stdint.h:202:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "PTRDIFF_MIN", "ns": 0, "location": "/usr/include/stdint.h:209:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "PTRDIFF_MAX", "ns": 0, "location": "/usr/include/stdint.h:210:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINT_FAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:181:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INTPTR_MIN", "ns": 0, "location": "/usr/include/stdint.h:186:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INTPTR_MAX", "ns": 0, "location": "/usr/include/stdint.h:187:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINTPTR_MAX", "ns": 0, "location": "/usr/include/stdint.h:188:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "WINT_MIN", "ns": 0, "location": "/usr/include/stdint.h:244:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "WINT_MAX", "ns": 0, "location": "/usr/include/stdint.h:245:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "SIG_ATOMIC_MIN", "ns": 0, "location": "/usr/include/stdint.h:222:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "SIG_ATOMIC_MAX", "ns": 0, "location": "/usr/include/stdint.h:223:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "SIZE_MAX", "ns": 0, "location": "/usr/include/stdint.h:227:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "WCHAR_MIN", "ns": 0, "location": "/usr/include/stdint.h:239:11", "type": { "tag": ":unsigned-long-long", "bit-size": 64, "bit-alignment": 64 }, "value": 0 },
{ "tag": "const", "name": "WCHAR_MAX", "ns": 0, "location": "/usr/include/stdint.h:240:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "_ATFILE_SOURCE", "ns": 0, "location": "/usr/include/features.h:326:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX_IMPLICITLY", "ns": 0, "location": "/usr/include/features.h:260:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "_POSIX_C_SOURCE", "ns": 0, "location": "/usr/include/features.h:265:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 200809 },
{ "tag": "const", "name": "_POSIX_SOURCE", "ns": 0, "location": "/usr/include/features.h:263:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__STDC_IEC_559_COMPLEX__", "ns": 0, "location": "/usr/include/stdc-predef.h:49:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__RLIM_T_MATCHES_RLIM64_T", "ns": 0, "location": "/usr/include/bits/typesizes.h:86:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__INO_T_MATCHES_INO64_T", "ns": 0, "location": "/usr/include/bits/typesizes.h:83:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__STDC_IEC_559__", "ns": 0, "location": "/usr/include/stdc-predef.h:41:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__FD_SETSIZE", "ns": 0, "location": "/usr/include/bits/typesizes.h:92:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1024 },
{ "tag": "const", "name": "_STDC_PREDEF_H", "ns": 0, "location": "/usr/include/stdc-predef.h:19:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__SSIZE_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:73:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "RENDERDOC_ShaderDebugMagicValue_bytearray", "ns": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:63:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 32 },
{ "tag": "const", "name": "__OFF_T_MATCHES_OFF64_T", "ns": 0, "location": "/usr/include/bits/typesizes.h:80:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__CPU_MASK_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:74:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "RENDERDOC_ShaderDebugMagicValue_truncated", "ns": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:69:9", "type": { "tag": ":unsigned-long-long", "bit-size": 64, "bit-alignment": 64 }, "value": 5216688378538513696 },
{ "tag": "const", "name": "RENDERDOC_ShaderDebugMagicValue_struct", "ns": 0, "location": "/home/jay/quicklisp/local-projects/cl-renderdoc/spec/renderdoc_app.h:57:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -357411552 },
{ "tag": "const", "name": "_DEFAULT_SOURCE", "ns": 0, "location": "/usr/include/features.h:221:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__flexarr", "ns": 0, "location": "/usr/include/sys/cdefs.h:143:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__glibc_c99_flexarr_available", "ns": 0, "location": "/usr/include/sys/cdefs.h:144:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__attribute_malloc__", "ns": 0, "location": "/usr/include/sys/cdefs.h:210:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__ptr_t", "ns": 0, "location": "/usr/include/sys/cdefs.h:109:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__BEGIN_DECLS", "ns": 0, "location": "/usr/include/sys/cdefs.h:117:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__intptr_t_defined", "ns": 0, "location": "/usr/include/stdint.h:88:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__END_DECLS", "ns": 0, "location": "/usr/include/sys/cdefs.h:118:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__THROW", "ns": 0, "location": "/usr/include/sys/cdefs.h:82:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__THROWNL", "ns": 0, "location": "/usr/include/sys/cdefs.h:83:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__STDC_ISO_10646__", "ns": 0, "location": "/usr/include/stdc-predef.h:58:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 201706 },
{ "tag": "const", "name": "__GNU_LIBRARY__", "ns": 0, "location": "/usr/include/features.h:415:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 6 },
{ "tag": "const", "name": "__GLIBC__", "ns": 0, "location": "/usr/include/features.h:419:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2 },
{ "tag": "const", "name": "__GLIBC_MINOR__", "ns": 0, "location": "/usr/include/features.h:420:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 28 },
{ "tag": "const", "name": "_SYS_CDEFS_H", "ns": 0, "location": "/usr/include/sys/cdefs.h:19:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "UINT_LEAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:145:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "INT_LEAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:142:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT_LEAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:141:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INT_LEAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:140:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 32767 },
{ "tag": "const", "name": "INT_FAST16_MIN", "ns": 0, "location": "/usr/include/stdint.h:154:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "INT_FAST8_MIN", "ns": 0, "location": "/usr/include/stdint.h:152:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "UINT_LEAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:148:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINT_LEAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:147:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_LEAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:146:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "INT_FAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:164:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT_FAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:162:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "INT_FAST64_MIN", "ns": 0, "location": "/usr/include/stdint.h:160:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__KERNEL_STRICT_NAMES", "ns": 0, "location": "/usr/include/features.h:147:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "INT_FAST32_MIN", "ns": 0, "location": "/usr/include/stdint.h:155:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__GLIBC_USE_DEPRECATED_GETS", "ns": 0, "location": "/usr/include/features.h:399:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "UINT_FAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:176:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "UINT_FAST16_MAX", "ns": 0, "location": "/usr/include/stdint.h:175:11", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "__USE_FORTIFY_LEVEL", "ns": 0, "location": "/usr/include/features.h:391:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "UINT_FAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:173:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "__USE_MISC", "ns": 0, "location": "/usr/include/features.h:368:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "INT_FAST64_MAX", "ns": 0, "location": "/usr/include/stdint.h:170:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "__USE_ATFILE", "ns": 0, "location": "/usr/include/features.h:372:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "INT_FAST32_MAX", "ns": 0, "location": "/usr/include/stdint.h:165:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "INT32_MIN", "ns": 0, "location": "/usr/include/stdint.h:118:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INT16_MIN", "ns": 0, "location": "/usr/include/stdint.h:117:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -32768 },
{ "tag": "const", "name": "INT8_MIN", "ns": 0, "location": "/usr/include/stdint.h:116:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "INT64_MAX", "ns": 0, "location": "/usr/include/stdint.h:124:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "__USE_XOPEN2K8", "ns": 0, "location": "/usr/include/features.h:324:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "INT8_MAX", "ns": 0, "location": "/usr/include/stdint.h:121:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "INT32_MAX", "ns": 0, "location": "/usr/include/stdint.h:123:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 2147483647 },
{ "tag": "const", "name": "INT16_MAX", "ns": 0, "location": "/usr/include/stdint.h:122:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 32767 },
{ "tag": "const", "name": "INT64_MIN", "ns": 0, "location": "/usr/include/stdint.h:119:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__USE_XOPEN2K", "ns": 0, "location": "/usr/include/features.h:316:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX199506", "ns": 0, "location": "/usr/include/features.h:312:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "UINT64_MAX", "ns": 0, "location": "/usr/include/stdint.h:130:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -1 },
{ "tag": "const", "name": "UINT32_MAX", "ns": 0, "location": "/usr/include/stdint.h:129:10", "type": { "tag": ":unsigned-long", "bit-size": 32, "bit-alignment": 32 }, "value": 4294967295 },
{ "tag": "const", "name": "__USE_POSIX2", "ns": 0, "location": "/usr/include/features.h:304:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "UINT16_MAX", "ns": 0, "location": "/usr/include/stdint.h:128:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 65535 },
{ "tag": "const", "name": "__attribute_const__", "ns": 0, "location": "/usr/include/sys/cdefs.h:235:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__USE_POSIX199309", "ns": 0, "location": "/usr/include/features.h:308:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__attribute_pure__", "ns": 0, "location": "/usr/include/sys/cdefs.h:228:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "UINT8_MAX", "ns": 0, "location": "/usr/include/stdint.h:127:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 255 },
{ "tag": "const", "name": "INT_LEAST8_MAX", "ns": 0, "location": "/usr/include/stdint.h:139:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 127 },
{ "tag": "const", "name": "__USE_POSIX", "ns": 0, "location": "/usr/include/features.h:300:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__attribute_used__", "ns": 0, "location": "/usr/include/sys/cdefs.h:245:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "INT_LEAST64_MIN", "ns": 0, "location": "/usr/include/stdint.h:137:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 0 },
{ "tag": "const", "name": "__USE_ISOC99", "ns": 0, "location": "/usr/include/features.h:320:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "INT_LEAST32_MIN", "ns": 0, "location": "/usr/include/stdint.h:136:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -2147483648 },
{ "tag": "const", "name": "INT_LEAST8_MIN", "ns": 0, "location": "/usr/include/stdint.h:134:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -128 },
{ "tag": "const", "name": "__USE_ISOC95", "ns": 0, "location": "/usr/include/features.h:318:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "INT_LEAST16_MIN", "ns": 0, "location": "/usr/include/stdint.h:135:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": -32768 },
{ "tag": "const", "name": "__WORDSIZE_TIME64_COMPAT32", "ns": 0, "location": "/usr/include/bits/wordsize.h:12:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__USE_ISOC11", "ns": 0, "location": "/usr/include/features.h:227:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "_FEATURES_H", "ns": 0, "location": "/usr/include/features.h:19:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__WORDSIZE", "ns": 0, "location": "/usr/include/bits/wordsize.h:4:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 64 },
{ "tag": "const", "name": "_STDINT_H", "ns": 0, "location": "/usr/include/stdint.h:23:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__CLANG_STDINT_H", "ns": 0, "location": "/usr/lib/clang/7.0.1/include/stdint.h:26:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SYSCALL_WORDSIZE", "ns": 0, "location": "/usr/include/bits/wordsize.h:14:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 64 },
{ "tag": "const", "name": "__restrict_arr", "ns": 0, "location": "/usr/include/sys/cdefs.h:393:12", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__attribute_nonstring__", "ns": 0, "location": "/usr/include/sys/cdefs.h:431:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__fortify_function", "ns": 0, "location": "/usr/include/sys/cdefs.h:356:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:72:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__extern_always_inline", "ns": 0, "location": "/usr/include/sys/cdefs.h:351:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SUSECONDS_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:66:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__USECONDS_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:65:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__CLOCK_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:63:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__TIME_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:64:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__DADDR_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:67:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__BLKSIZE_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:71:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__TIMER_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:70:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__HAVE_GENERIC_SELECTION", "ns": 0, "location": "/usr/include/sys/cdefs.h:502:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__BLKCNT64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:57:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__BLKCNT_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:56:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__RLIM64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:55:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSFILCNT_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:60:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSBLKCNT64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:59:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__MODE_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:43:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__KEY_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:68:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSBLKCNT_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:58:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__NLINK_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:45:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__INO_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:41:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSFILCNT64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:61:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__INO64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:42:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__PID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:53:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__CLOCKID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:69:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__ID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:62:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__RLIM_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:54:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__attribute_noinline__", "ns": 0, "location": "/usr/include/sys/cdefs.h:246:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__OFF_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:51:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__FSWORD_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:46:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__OFF64_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:52:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "_BITS_TYPESIZES_H", "ns": 0, "location": "/usr/include/bits/typesizes.h:24:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 }, "value": 1 },
{ "tag": "const", "name": "__S64_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:133:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__U64_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:134:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__UID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:39:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__GID_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:40:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SYSCALL_SLONG_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:34:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__DEV_T_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:38:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SYSCALL_ULONG_TYPE", "ns": 0, "location": "/usr/include/bits/typesizes.h:35:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__wur", "ns": 0, "location": "/usr/include/sys/cdefs.h:310:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__ULONGWORD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:113:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SQUAD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:127:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__always_inline", "ns": 0, "location": "/usr/include/sys/cdefs.h:322:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__UQUAD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:128:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__U32_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:111:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__attribute_warn_unused_result__", "ns": 0, "location": "/usr/include/sys/cdefs.h:307:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SLONGWORD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:112:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SLONG32_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:131:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__ULONG32_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:132:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__extern_inline", "ns": 0, "location": "/usr/include/sys/cdefs.h:350:11", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__attribute_artificial__", "ns": 0, "location": "/usr/include/sys/cdefs.h:330:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__SWORD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:129:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__UWORD_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:130:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__attribute_deprecated__", "ns": 0, "location": "/usr/include/sys/cdefs.h:253:10", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__U16_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:109:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "__S32_TYPE", "ns": 0, "location": "/usr/include/bits/types.h:110:9", "type": { "tag": ":long", "bit-size": 32, "bit-alignment": 32 } }
]
